app            = "plantathome-mysql"
primary_region = "sin"

[build]
  image = "mysql:8.0"

[env]
  MYSQL_DATABASE = "railway"
  MYSQL_USER     = "railway"

[[mounts]]
  source      = "mysql_data"
  destination = "/var/lib/mysql"

[[services]]
  internal_port = 3306
  protocol      = "tcp"
