<?php

namespace Marvel\Services\TestDataCleanup;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Derived pricing artefacts: the per-city availability projection, price-sheet import batches
 * and market snapshots. All of it is REGENERATED from vendor inventory by the recompute, so
 * clearing it is the safest module here — it repairs itself.
 */
class PricesCleaner implements CleanerContract
{
    public function key(): string { return 'prices'; }

    public function label(): string { return 'Prices & Availability'; }

    public function description(): string
    {
        return 'Clears the derived city-availability projection, price-sheet import batches and '
             . 'market price snapshots. Vendor inventory and the catalog are untouched; the '
             . 'projection is rebuilt from live inventory right after.';
    }

    public function stats(): array
    {
        return [
            'city_availability' => Schema::hasTable('product_city_availability') ? DB::table('product_city_availability')->count() : 0,
            'import_batches'    => Schema::hasTable('price_import_batches') ? DB::table('price_import_batches')->count() : 0,
            'market_snapshots'  => Schema::hasTable('market_price_snapshots') ? DB::table('market_price_snapshots')->count() : 0,
        ];
    }

    public function plan(array $scope): CleanupPlan
    {
        $plan = new CleanupPlan($this->key(), $scope);
        $targets = (array) ($scope['targets'] ?? ['city_availability', 'import_batches', 'market_snapshots']);

        if (in_array('city_availability', $targets, true) && Schema::hasTable('product_city_availability')) {
            $plan->step('product_city_availability', DB::table('product_city_availability')->pluck('id')->all(), 'id', 'regenerated by recompute');
        }
        if (in_array('import_batches', $targets, true) && Schema::hasTable('price_import_batches')) {
            $ids = DB::table('price_import_batches')->pluck('id')->all();
            if ($ids && Schema::hasTable('vendor_product_prices')) {
                // The rows an import created stay; only the batch record goes.
                $plan->nullify('vendor_product_prices', 'import_batch_id', $ids);
            }
            $plan->step('price_import_batches', $ids, 'id');
        }
        if (in_array('market_snapshots', $targets, true) && Schema::hasTable('market_price_snapshots')) {
            $plan->step('market_price_snapshots', DB::table('market_price_snapshots')->pluck('id')->all(), 'id');
        }
        return $plan;
    }
}
